function [sys3] = %lfr_m_s(sys1,sys2)

// Overloads multiplication
// The operands are: lfr-object , constant-object
// This file is not generated by gen_op_files.pl

if maxi(size(sys2)) == 1;
   sys3 = %lfr_m_lfr(lfr(sys2),sys1);
else
   sys3 = %lfr_m_lfr(sys1,lfr(sys2));
end;

endfunction
